baseURL = 'http://example.org/'
title = 'My New Hugo Site'

languageCode = "en"
defaultContentLanguage = "en"


[languages]
  [languages.en]
    title = "Repro"
    languageName = "English"
    contentDir = "content/en"
    weight = 1

  [languages.zh_CN]
    title = "Repro"
    weight = 2
    languageName = "简体中文"
    contentDir = "content/zh_CN"

[outputFormats]
  [outputFormats.metadata]
    baseName = "metadata"
    mediaType = "text/html"
    isPlainText = true
    notAlternative = true

[outputs]
    home = ["HTML", "metadata"]