baseURL = 'http://example.org/'
title = 'My New Hugo Site'

languageCode = "en"
defaultContentLanguage = "en"

disableKinds = ['taxonomy','term','sitemap']

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    title = "Repro"
    weight = 1

  [languages.zh_CN]
    contentDir = "content/zh_CN"
    languageName = "简体中文"
    title = "Repro"
    weight = 2

[outputFormats]
  [outputFormats.metadata]
    baseName = "metadata"
    isPlainText = true
    mediaType = "text/html"
    notAlternative = true

[outputs]
    home = ["HTML", "metadata"]
